# Use Dockerized infrastructure
sudo: false

# Use node_js environnement
language: node_js
node_js:
  - "6"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json
    - NODE_ENV=CI

install:
  - npm install

script:
  - npm test

env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1 

before_deploy:
  # redirect to /dev/null, see https://github.com/m-lab/travis/pull/21
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc

deploy:
  - provider: script
    script: bash ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: deploy-to-gcloud
  - provider: script
    script: bash ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master

